accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from .views import LogoutView, RegisterView

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register')
]

rango/urls.py
from django.conf.urls import url, include

from .views import (
	IndexView,
	AboutView,
	CategoryList,
	CategoryDetail,
	CategoryCreate,
	CategoryUpdate,
	CategoryDelete,
	PageCreate,
	PageUpdate,
	PageDelete,
)

app_name = 'rango'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^categories/$', CategoryList.as_view(), name='categories'),
    url(r'^category/(?P<slug>[\w\-]+)/$', CategoryDetail.as_view(), name='category'),
    url(r'^categories/add-category/$', CategoryCreate.as_view(), name='add_category'),
    url(r'^category/(?P<slug>[\w\-]+)/update/$', CategoryUpdate.as_view(), name='edit_category'),
	url(r'^category/(?P<slug>[\w\-]+)/delete/$', CategoryDelete.as_view(), name='delete_category'),
    url(r'^category/(?P<slug>[\w\-]+)/add-page/$', PageCreate.as_view(), name='add_page'),
    url(r'^page/(?P<slug>[\w\-]+)/update/$', PageUpdate.as_view(), name='edit_page'),
	url(r'^page/(?P<slug>[\w\-]+)/delete', PageDelete.as_view(), name='delete_page'),
]

tango/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'', include('rango.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Category(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('rango:category', kwargs={'slug': self.slug})


class Page(models.Model):
    category = models.ForeignKey(Category)
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField(max_length=200)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Page, self).save(*args, **kwargs)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rango:category', kwargs={'slug': self.category.slug})

rango/forms.py
from django import forms

from .models import Category, Page


class CategoryForm(forms.ModelForm):
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': ''}


class PageForm(forms.ModelForm):
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Page
        fields = ['title', 'url']

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic.edit import FormView
from django.urls import reverse_lazy


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('rango:index')


class RegisterView(FormView):
    template_name = 'accounts/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('rango:index')

    def form_valid(self, form):
        new_user = form.save()
        username = new_user.username
        password = form.cleaned_data['password1']
        authenticated_user = authenticate(username=username, password=password)
        login(self.request, authenticated_user)
        return super(RegisterView, self).form_valid(form)

rango/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView


from .models import Category, Page
from .forms import CategoryForm, PageForm


class IndexView(TemplateView):
    template_name = "rango/index.html"


class AboutView(TemplateView):
    template_name = "rango/about.html"


class CategoryList(ListView):
    model = Category
    context_object_name = 'categories'


class CategoryDetail(DetailView):
    model = Category
    context_object_name = 'category'

    def get_object(self):
        category = super(CategoryDetail, self).get_object()
        category.views += 1
        category.save()
        return category


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name_suffix = '_create'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CategoryCreate, self).form_valid(form)


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name_suffix = '_update'

    def get_object(self):
        category = super(CategoryUpdate, self).get_object()
        if category.owner != self.request.user:
            raise Http404("Access is denied")
        return category


class CategoryDelete(LoginRequiredMixin, DeleteView):
    model = Category
    context_object_name = 'category'
    template_name_suffix = '_delete'
    success_url = reverse_lazy('rango:categories')

    def get_object(self):
        category = super(CategoryDelete, self).get_object()
        if category.owner != self.request.user:
            raise Http404("Access is denied")
        return category


class PageCreate(LoginRequiredMixin, CreateView):
    model = Page
    context_object_name = 'page'
    form_class = PageForm
    template_name_suffix = '_create'

    def get_context_data(self, **kwargs):
        context = super(PageCreate, self).get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

    def form_valid(self, form):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        form.instance.owner = self.request.user
        form.instance.category = self.category
        form.instance.views = 0
        return super(PageCreate, self).form_valid(form)


class PageUpdate(LoginRequiredMixin, UpdateView):
    model = Page
    context_object_name = 'page'
    form_class = PageForm
    template_name_suffix = '_update'

    def get_object(self):
        page = super(PageUpdate, self).get_object()
        if page.owner != self.request.user:
            raise Http404("Access is denied")
        return page


class PageDelete(LoginRequiredMixin, DeleteView):
    model = Page
    context_object_name = 'page'
    template_name_suffix = '_delete'

    def get_object(self):
        page = super(PageDelete, self).get_object()
        if page.owner != self.request.user:
            raise Http404("Access is denied")
        return page

    def get_success_url(self):
        return reverse('rango:category', kwargs={'slug': self.object.category.slug})

accounts/templates/accounts/login.html
{% extends 'rango/base.html' %}
{% load bootstrap3 %}

{% block title %}Log in{% endblock %}

{% block header %}
  <h2>Log in to your account</h2>
{% endblock %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'rango:index' %}" class="btn btn-default">Cancel</a>
    <input type="hidden" name="next" value="{% url 'rango:index' %}">
  </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'rango/base.html' %}
{% load bootstrap3 %}

{% block title %}Log in{% endblock %}

{% block header %}
  <h2>Create new account</h2>
{% endblock %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'rango:index' %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

rango/templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title %}About{% endblock %}

{% block header %}
  <div class="jumbotron">
    <h1>Rango</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos ut, ullam commodi quam dolore, totam est pariatur ab corrupti distinctio esse similique illum optio magnam delectus sed autem. Iste quam doloremque eos, ex expedita quod repellendus atque rerum maiores neque.</p>
    <img src="{{ MEDIA_URL }}cat.png" alt="Cat">
  </div>
{% endblock %}

rango/templates/rango/base.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>{% block title %}Rango{% endblock %}</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <nav class="navbar navbar-light navbar-static-top">
    <div class="container">

      <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" area-expanded="false" aria-controls="navbar">
          <span class="glyphicon glyphicon-menu-hamburger"></span>
        </button>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'rango:index' %}">Home</a></li>
          <li><a href="{% url 'rango:categories' %}">Categories</a></li>
          <li><a href="{% url 'rango:about' %}">About</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>{{ user.username|capfirst }}</a></li>
            <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Log out</a></li>
          {% else %}
            <li><a href="{% url 'accounts:register' %}"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Sign Up</a></li>
            <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;&nbsp;Log in</a></li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

  <div class="container">
    <div class="page-header">
      {% block header %}{% endblock %}
    </div>
    <div>
      {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>

rango/templates/rango/category_create.html
{% extends "rango/base.html" %}
{% load bootstrap3 %}

{% block title %}Add category{% endblock %}

{% block content %}
  <div class="panel panel-success">
    <div class="panel-heading">Add new category</div>
  </div>

  <form action="" method="post" class="form">
		{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url 'rango:categories' %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

rango/templates/rango/category_delete.html
{% extends 'rango/base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
  <div class="panel panel-danger">
    <div class="panel-heading">Delete Category</div>
    <div class="panel-body">{{ category }}</div>
  </div>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'rango:categories' %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

rango/templates/rango/category_detail.html
{% extends "rango/base.html" %}

{% block title %}{{ category.name }}{% endblock %}

{% block header %}
  <h2>{{ category.name|upper }}</h2>
{% endblock %}

{% block content %}
  <ul class="list-group">
    {% for page in category.page_set.all %}
      <li class="list-group-item">
        <a href="{{ page.url }}" target="_blank">{{ page.title }}</a>
        {% if page.owner == user %}
          <a href="{% url 'rango:edit_page' page.slug %}" class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-edit"></a>
          <a href="{% url 'rango:delete_page' page.slug %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></a>
        {% endif %}
      </li>
    {% empty %}
      <li class="list-group-item list-group-item-danger">No pages currently in category</li>
    {% endfor %}
  </ul>

  {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> Add new page</a>
  {% endif %}
{% endblock %}

rango/templates/rango/category_list.html
{% extends "rango/base.html" %}

{% block title %}Categories{% endblock %}

{% block header %}
  <h1>List categories</h1>
{% endblock %}

{% block content %}
  <ul class="list-group">
    {% for category in categories %}
      <li class="list-group-item">
        <a href="{% url 'rango:category' category.slug %}">{{ category.name }} <span class="badge">{{ category.views }}</span></a>
        {% if category.owner == user %}
          <a href="{% url 'rango:edit_category' category.slug %}" class="btn btn-warning btn-xs"><span class="glyphicon glyphicon-edit"></span></a>
          <a href="{% url 'rango:delete_category' category.slug %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></a>
        {% endif %}
      </li>
    {% empty %}
      <li class="list-group-item">There are no categories present</li>
    {% endfor %}
  </ul>

  {% if user.is_authenticated %}
    <a href="{% url 'rango:add_category' %}" class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> Add new category</a>
  {% endif %}

{% endblock %}

rango/templates/rango/category_update.html
{% extends "rango/base.html" %}
{% load bootstrap3 %}

{% block title %}Edit Category{% endblock %}

{% block content %}
  <div class="panel panel-warning">
    <div class="panel-heading">Edit Category</div>
  </div>

	<form action="" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" value="Update" class="btn btn-warning">
		<a href="{% url 'rango:categories' %}" class="btn btn-default">Cancel</a>
	</form>
{% endblock %}

rango/templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block header %}
  <div class="jumbotron">
    <h1 class="display-3">Rango</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis esse ratione facere eius temporibus, perferendis enim in, atque obcaecati est qui, magnam aliquid! Aspernatur, at. Alias expedita quidem voluptatibus, saepe aut hic aspernatur atque. Id ea cum quasi odio quaerat, dolores vero deleniti, obcaecati temporibus recusandae eveniet consectetur libero nihil.</p>
    <p><a href="{% url 'accounts:register' %}" class="btn btn-success btn-lg">Register</a></p>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4">
      <h2>Subheading</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga officia cumque rerum exercitationem dignissimos, omnis culpa soluta suscipit sed, animi!</p>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <h2>Subheading</h2>
      <p>Quia autem aperiam quam molestiae odit rerum quis perferendis aut in saepe, doloribus ullam molestias! Temporibus pariatur magni, odit velit.</p>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <h2>Subheading</h2>
      <p>Et distinctio esse ratione aliquam, blanditiis officiis quam nobis rem! Saepe earum consequatur quae quidem iusto voluptatem quod deleniti praesentium!</p>
    </div>
  </div>
{% endblock %}

rango/templates/rango/page_create.html
{% extends "rango/base.html" %}
{% load bootstrap3 %}

{% block title %}Add Page{% endblock %}

{% block content %}
	<div class="panel panel-success">
		<div class="panel-heading">Add new page</div>
	</div>

	<form action="" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" value="Submit" class="btn btn-primary">
		<a href="{% url 'rango:category' category.slug %}" class="btn btn-default">Cancel</a>
	</form>
{% endblock %}

rango/templates/rango/page_delete.html
{% extends 'rango/base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
  <div class="panel panel-danger">
    <div class="panel-heading">Delete Page</div>
    <div class="panel-body">{{ page }}</div>
  </div>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'rango:category' page.category.slug %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}

rango/templates/rango/page_update.html
{% extends "rango/base.html" %}
{% load bootstrap3 %}

{% block title %}Edit page{% endblock %}

{% block content %}
  <div class="panel panel-warning">
    <div class="panel-heading">Edit Page</div>
  </div>

  <form action="" method="post" class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Update" class="btn btn-warning">
  	<a href="{% url 'rango:category' page.category.slug %}" class="btn btn-default">Cancel</a>
  </form>
{% endblock %}